### ISSUE TITLE
Franz download recipe

### ISSUE THREAD

**Issue by nilsbyte** [autopkg/andrewvalentine-recipes#18] opened 2019-02-07 13:32 UTC
It looks like the download recipe does not what it should do. My Franz is outdated but the recipes are executed. Can you take a look @andrewvalentine ?

**Comment by andrewvalentine** [comment] 2019-02-08 14:47
Fixed by 2eab9aa04365ed08390fe0c4fd196214b565a957

**Comment by nilsbyte** [comment] 2019-02-11 10:52
Problem with this is, that your script is downloading the latest release, but not the pre-releases. The internal update mechanism of Franz is getting the pre-releases. Want to change that in your script?

**Comment by andrewvalentine** [comment] 2019-02-12 10:52
That is by design, but I've now optimised all of the Franz recipes to leverage the `INCLUDE_PRERELEASES` function of `GitHubReleasesInfoProvider`. The `.download` specific commit is 87f445d7a701bb7da93025c3fbc7ed392a2d7b15.

**Comment by andrewvalentine** [comment] 2019-02-12 10:52
Fixed with 87f445d7a701bb7da93025c3fbc7ed392a2d7b15.

**Closed by andrewvalentine** 2019-02-12 10:52 UTC

**Comment by opus-nbo** [comment] 2019-02-27 09:03
I have tried it but it does not work. I just filled the string for the mentioned key with a 'true' in my override for the munki file. 

```
		<key>INCLUDE_PRERELEASES</key>
		<string>true</string>
```
